api_platform:
  defaults:
    pagination_client_enabled: true
    pagination_client_items_per_page: true
  eager_loading: false
  swagger:
    versions: [ 3 ]
    api_keys:
      JWT:
        name: Authorization
        type: header
